### ISSUE TITLE
hardcoded accounts

### ISSUE THREAD

**Issue by bitgamma** [luibo/KeycardForiPhone#3]
at https://github.com/luibo/KeycardForiPhone/blob/d28b6230bea06e57fd48b98c02cdadbb1323da28/KeycardSwiftIntegration/Controller/SelectWalletController.swift#L151

the accounts discovered on card are replaced by an hardcoded list.

**Comment by luibo** [comment]
Sorry, this was only for testing purposes. I'm updating the code as soon as
possible.

Il giorno mar 7 lug 2020 alle ore 15:48 Bitgamma <notifications@github.com>
ha scritto:

**Comment by luibo** [comment]
I just commited the fix, the discovered accounts list is no longer
hardcoded. As I said, that was only for testing purposes, as I needed to
test the APIs with addresses that I was sure had been used for at least one
transaction.

Regarding what we discussed earlier, I understood your explanation, in the
next few days I'm changing the app protocol for card reading, even
providing an option for the user to unpair the card from a device.
One more thing, It often happens that the card loses connection with the
device while it's been read, especially during long NFC sessions. I was
wondering if it's some hardware problem related to the card itself or if it
could be a software problem, related to the SDK or to iOS libraries for NFC
cards reading.

Il giorno mar 7 lug 2020 alle ore 15:50 Luigi Borchia <luigib96@gmail.com>
ha scritto:

**Comment by bitgamma** [comment]
this is most likely related to iOS itself. We tested on many Android phones and while result varies from model to model once you find the "sweet spot" it seems to be stable with no random drops. 

In particular certain operations consume more power and if the iPhone's NFC field is weak the card might no have enough power during these operations, thus losing connection. Of course it is very possible that the software stack has bugs too either in the firmware or in the SDK (but in the SDK there isn't much low-level stuff).

The hardware of the card itself is the same you can find in many bank cards or national IDs (including the antenna and the card body) so I would exclude the possibility that that could be the source of the problem.
